# This file has been autogenerated. Do not change by hand. 

#' Create a parameter object for the function getDbSccsData
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param useCustomCovariates          Create covariates from a custom table?
#' @param deleteCovariatesSmallCount   The minimum count for a covariate to appear in the data tobe
#'                                     kept.
#' @param studyStartDate               A calendar date specifying the minimum date where data is
#'                                     used.Date format is 'yyyymmdd'.
#' @param studyEndDate                 A calendar date specifying the maximum date where data is
#'                                     used.Date format is 'yyyymmdd'.
#' @param exposureIds                  A list of identifiers to define the exposures of interest.
#'                                     IfexposureTable = DRUG_ERA, exposureIds should be CONCEPT_ID.If
#'                                     exposureTable <> DRUG_ERA, exposureIds is used to selectthe
#'                                     cohort_concept_id in the cohort-like table. If noexposureIds are
#'                                     provided, all drugs or cohorts in theexposureTable are included
#'                                     as exposures.
#' @param customCovariateIds           A list of cohort definition IDS identifying the records inthe
#'                                     customCovariateTable to use for building customcovariates.
#'
#' @export
createGetDbSccsDataArgs <- function(useCustomCovariates = FALSE,
                                    deleteCovariatesSmallCount = 100,
                                    studyStartDate = "",
                                    studyEndDate = "",
                                    exposureIds = "exposureId",
                                    customCovariateIds = "") {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createGetDbSccsDataArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function createSccsEraData
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param naivePeriod                 The number of days at the start of a patient's observation
#'                                    periodthat should not be included in the risk calculations. Note
#'                                    thatthe naive period can be used to determine current
#'                                    covariatestatus right after the naive period, and whether an
#'                                    outcome isthe first one.
#' @param firstOutcomeOnly            Whether only the first occurrence of an outcome should
#'                                    beconsidered.
#' @param covariateSettings           Either an object of type covariateSettings as createdusing the
#'                                    createCovariateSettings function, or alist of such objects.
#' @param ageSettings                 An object of type ageSettings as created using
#'                                    thecreateAgeSettings function.
#' @param seasonalitySettings         An object of type seasonalitySettings as created using
#'                                    thecreateSeasonalitySettings function.
#' @param eventDependentObservation   Should the extension proposed by Farrington et al. be used
#'                                    toadjust for event-dependent observation time?
#'
#' @export
createCreateSccsEraDataArgs <- function(naivePeriod = 0,
                                        firstOutcomeOnly = FALSE,
                                        covariateSettings,
                                        ageSettings = createAgeSettings(includeAge = FALSE),
                                        seasonalitySettings = createSeasonalitySettings(includeSeasonality = FALSE),
                                        eventDependentObservation = FALSE) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createCreateSccsEraDataArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function fitSccsModel
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param prior     The prior used to fit the model. See createPrior fordetails.
#' @param control   The control object used to control the cross-validation used to determine
#'                  thehyperparameters of the prior (if applicable). SeecreateControl for details.
#'
#' @export
createFitSccsModelArgs <- function(prior = createPrior("laplace", useCrossValidation = TRUE),
                                   control = createControl(cvType = "auto",
                                                           selectorType = "byPid",
                                                           startingVariance = 0.1,
                                                           noiseLevel = "quiet")) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createFitSccsModelArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}
