# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convertToSccs <- function(cases, outcomes, eras, includeAge, ageOffset, ageDesignMatrix, includeSeason, includeCalendarTime, calendarTimeOffset, calendarTimeDesignMatrix, seasonDesignMatrix, timeCovariateCases, covariateSettingsList, eventDependentObservation, censorModel, scri, controlIntervalId, resultAndromeda) {
    invisible(.Call('_SelfControlledCaseSeries_convertToSccs', PACKAGE = 'SelfControlledCaseSeries', cases, outcomes, eras, includeAge, ageOffset, ageDesignMatrix, includeSeason, includeCalendarTime, calendarTimeOffset, calendarTimeDesignMatrix, seasonDesignMatrix, timeCovariateCases, covariateSettingsList, eventDependentObservation, censorModel, scri, controlIntervalId, resultAndromeda))
}

simulateSccsOutcomes <- function(cases, eras, baselineRates, eraRrs, includeAgeEffect, ageOffset, ageRrs, includeSeasonality, seasonRrs, includeCalendarTimeEffect, minCalendarTime, calendarTimeRrs) {
    .Call('_SelfControlledCaseSeries_simulateSccsOutcomes', PACKAGE = 'SelfControlledCaseSeries', cases, eras, baselineRates, eraRrs, includeAgeEffect, ageOffset, ageRrs, includeSeasonality, seasonRrs, includeCalendarTimeEffect, minCalendarTime, calendarTimeRrs)
}

testEwad <- function(p, present, astart, aend, start, end) {
    .Call('_SelfControlledCaseSeries_testEwad', PACKAGE = 'SelfControlledCaseSeries', p, present, astart, aend, start, end)
}

testEwid <- function(p, present, astart, aend, start, end) {
    .Call('_SelfControlledCaseSeries_testEwid', PACKAGE = 'SelfControlledCaseSeries', p, present, astart, aend, start, end)
}

testEgad <- function(p, present, astart, aend, start, end) {
    .Call('_SelfControlledCaseSeries_testEgad', PACKAGE = 'SelfControlledCaseSeries', p, present, astart, aend, start, end)
}

testEgid <- function(p, present, astart, aend, start, end) {
    .Call('_SelfControlledCaseSeries_testEgid', PACKAGE = 'SelfControlledCaseSeries', p, present, astart, aend, start, end)
}

