# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convertToSccs <- function(cases, eras, outcomeId, naivePeriod, firstOutcomeOnly, includeAge, ageOffset, ageDesignMatrix, minAge, maxAge, includeSeason, seasonDesignMatrix, ageSeasonsCases, covariateSettingsList, eventDependentObservation, censorModel) {
    .Call('_SelfControlledCaseSeries_convertToSccs', PACKAGE = 'SelfControlledCaseSeries', cases, eras, outcomeId, naivePeriod, firstOutcomeOnly, includeAge, ageOffset, ageDesignMatrix, minAge, maxAge, includeSeason, seasonDesignMatrix, ageSeasonsCases, covariateSettingsList, eventDependentObservation, censorModel)
}

simulateSccsOutcomes <- function(cases, eras, baselineRates, eraRrs, includeAge, ageOffset, ageRrs, includeSeasonality, seasonRrs) {
    .Call('_SelfControlledCaseSeries_simulateSccsOutcomes', PACKAGE = 'SelfControlledCaseSeries', cases, eras, baselineRates, eraRrs, includeAge, ageOffset, ageRrs, includeSeasonality, seasonRrs)
}

testEwad <- function(p, present, astart, aend, start, end) {
    .Call('_SelfControlledCaseSeries_testEwad', PACKAGE = 'SelfControlledCaseSeries', p, present, astart, aend, start, end)
}

testEwid <- function(p, present, astart, aend, start, end) {
    .Call('_SelfControlledCaseSeries_testEwid', PACKAGE = 'SelfControlledCaseSeries', p, present, astart, aend, start, end)
}

testEgad <- function(p, present, astart, aend, start, end) {
    .Call('_SelfControlledCaseSeries_testEgad', PACKAGE = 'SelfControlledCaseSeries', p, present, astart, aend, start, end)
}

testEgid <- function(p, present, astart, aend, start, end) {
    .Call('_SelfControlledCaseSeries_testEgid', PACKAGE = 'SelfControlledCaseSeries', p, present, astart, aend, start, end)
}

