# @file PackageMaintenance
#
# Copyright 2018 Observational Health Data Sciences and Informatics
#
# This file is part of SelfControlledCaseSeries
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code
OhdsiRTools::formatRFolder()
OhdsiRTools::checkUsagePackage("SelfControlledCaseSeries")
OhdsiRTools::updateCopyrightYearFolder()

# Create manual and vignette
if (.Platform$OS.type == "unix") {
  system("rm extras/SelfControlledCaseSeries.pdf")
  system("R CMD Rd2pdf ./ --output=extras/SelfControlledCaseSeries.pdf")
} else {
  shell("rm extras/SelfControlledCaseSeries.pdf")
  shell("R CMD Rd2pdf ./ --output=extras/SelfControlledCaseSeries.pdf")
}

rmarkdown::render("vignettes/SingleStudies.Rmd",
                  output_file = "../inst/doc/SingleStudies.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/MultipleAnalyses.Rmd",
                  output_file = "../inst/doc/MultipleAnalyses.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

pkgdown::build_site()

# Create arg functions:
library(SelfControlledCaseSeries)
rCode <- c("# This file has been autogenerated. Do not change by hand. ")
rCode <- OhdsiRTools::createArgFunction("getDbSccsData",
                                        excludeArgs = c("connectionDetails",
                                                        "cdmDatabaseSchema",
                                                        "oracleTempSchema",
                                                        "exposureDatabaseSchema",
                                                        "exposureTable",
                                                        "outcomeDatabaseSchema",
                                                        "outcomeTable",
                                                        "customCovariateDatabaseSchema",
                                                        "customCovariateTable",
                                                        "nestingCohortDatabaseSchema",
                                                        "nestingCohortTable",
                                                        "cdmVersion",
                                                        "exposureIds",
                                                        "outcomeIds",
                                                        "customCovariateIds"),
                                        addArgs = list(exposureIds = "exposureId",
                                                       customCovariateIds = ""),
                                        rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("createSccsEraData",
                                        excludeArgs = c("sccsData", "outcomeId"),
                                        rCode = rCode)
rCode <- OhdsiRTools::createArgFunction("fitSccsModel",
                                        excludeArgs = c("sccsEraData", "population"),
                                        rCode = rCode)
writeLines(rCode, "r/CreateArgFunctions.R")
OhdsiRTools::formatRFile("r/CreateArgFunctions.R")
